import { AnalysisCard } from '@/types/analysis';

export const sampleAnalyses: AnalysisCard[] = [
  // Recently Published
  {
    id: '1',
    session_id: 'sample_session_1',
    title: 'Amazon Rainforest Deforestation Analysis 2020-2024',
    description: 'Comprehensive NDVI analysis showing vegetation loss patterns in the Brazilian Amazon over the past 4 years.',
    query: 'What is the vegetation change from 2020 to 2024 in the Amazon rainforest?',
    coordinates: {
      southwest_lat: -10.0,
      southwest_lon: -70.0,
      northeast_lat: 5.0,
      northeast_lon: -50.0,
    },
    location_name: 'Amazon Basin, Brazil',
    start_year: 2020,
    end_year: 2024,
    created_at: '2024-08-01T10:30:00Z',
    author: 'Dr. Maria Santos',
    likes: 156,
    shares: 43,
    views: 2341,
    tags: ['deforestation', 'amazon', 'climate-change', 'conservation'],
    thumbnail_url: 'https://images.unsplash.com/photo-1574452969969-7fb3bbef4056?w=400&h=300&fit=crop',
    category: 'recently_published',
    is_public: true,
  },
  {
    id: '2',
    session_id: 'sample_session_2',
    title: 'Urban Green Space Expansion in Singapore',
    description: 'Analysis of urban vegetation growth and green infrastructure development in Singapore\'s city planning.',
    query: 'How has urban vegetation changed in Singapore from 2018 to 2024?',
    coordinates: {
      southwest_lat: 1.2966,
      southwest_lon: 103.6764,
      northeast_lat: 1.4504,
      northeast_lon: 104.0120,
    },
    location_name: 'Singapore',
    start_year: 2018,
    end_year: 2024,
    created_at: '2024-07-28T14:15:00Z',
    author: 'Dr. Wei Chen',
    likes: 89,
    shares: 22,
    views: 1567,
    tags: ['urban-planning', 'green-cities', 'sustainability'],
    thumbnail_url: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&h=300&fit=crop',
    category: 'recently_published',
    is_public: true,
  },
  {
    id: '3',
    session_id: 'sample_session_3',
    title: 'Alpine Vegetation Response to Climate Change',
    description: 'Swiss Alps vegetation monitoring showing upward migration of plant species due to warming temperatures.',
    query: 'What are the vegetation changes in the Swiss Alps from 2015 to 2024?',
    coordinates: {
      southwest_lat: 46.2,
      southwest_lon: 6.0,
      northeast_lat: 47.8,
      northeast_lon: 10.5,
    },
    location_name: 'Swiss Alps',
    start_year: 2015,
    end_year: 2024,
    created_at: '2024-07-25T09:45:00Z',
    author: 'Prof. Hans Mueller',
    likes: 201,
    shares: 67,
    views: 3456,
    tags: ['alpine', 'climate-change', 'elevation', 'switzerland'],
    thumbnail_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    category: 'recently_published',
    is_public: true,
  },
  {
    id: '4',
    session_id: 'sample_session_4',
    title: 'Sahel Green Belt Initiative Progress',
    description: 'Monitoring the Great Green Wall project\'s impact on vegetation recovery across the Sahel region.',
    query: 'What is the vegetation recovery progress in the Sahel from 2017 to 2024?',
    coordinates: {
      southwest_lat: 10.0,
      southwest_lon: -18.0,
      northeast_lat: 18.0,
      northeast_lon: 22.0,
    },
    location_name: 'Sahel Region, Africa',
    start_year: 2017,
    end_year: 2024,
    created_at: '2024-07-22T16:20:00Z',
    author: 'Dr. Aminata Kone',
    likes: 134,
    shares: 56,
    views: 2890,
    tags: ['sahel', 'reforestation', 'desertification', 'africa'],
    thumbnail_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
    category: 'recently_published',
    is_public: true,
  },

  // Community Research
  {
    id: '5',
    session_id: 'sample_session_5',
    title: 'Global Mangrove Forest Health Assessment',
    description: 'Comprehensive analysis of mangrove ecosystems worldwide, tracking conservation efforts and climate impacts.',
    query: 'How have mangrove forests changed globally from 2015 to 2023?',
    coordinates: {
      southwest_lat: -30.0,
      southwest_lon: -180.0,
      northeast_lat: 30.0,
      northeast_lon: 180.0,
    },
    location_name: 'Global Coastal Regions',
    start_year: 2015,
    end_year: 2023,
    created_at: '2024-06-15T11:30:00Z',
    author: 'Marine Conservation Institute',
    likes: 445,
    shares: 189,
    views: 8934,
    tags: ['mangroves', 'coastal', 'conservation', 'global'],
    thumbnail_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
    category: 'community_research',
    is_public: true,
  },
  {
    id: '6',
    session_id: 'sample_session_6',
    title: 'Arctic Tundra Vegetation Shifts',
    description: 'Long-term study of Arctic vegetation changes due to permafrost thaw and temperature increases.',
    query: 'What are the vegetation changes in Arctic tundra from 2015 to 2024?',
    coordinates: {
      southwest_lat: 65.0,
      southwest_lon: -170.0,
      northeast_lat: 85.0,
      northeast_lon: 170.0,
    },
    location_name: 'Arctic Tundra',
    start_year: 2015,
    end_year: 2024,
    created_at: '2024-05-20T08:15:00Z',
    author: 'Arctic Research Consortium',
    likes: 312,
    shares: 98,
    views: 6123,
    tags: ['arctic', 'tundra', 'permafrost', 'climate'],
    thumbnail_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
    category: 'community_research',
    is_public: true,
  },
  {
    id: '7',
    session_id: 'sample_session_7',
    title: 'Mediterranean Drought Impact Study',
    description: 'Analysis of drought effects on Mediterranean vegetation and agricultural productivity.',
    query: 'How has drought affected vegetation in the Mediterranean from 2019 to 2024?',
    coordinates: {
      southwest_lat: 30.0,
      southwest_lon: -10.0,
      northeast_lat: 45.0,
      northeast_lon: 45.0,
    },
    location_name: 'Mediterranean Basin',
    start_year: 2019,
    end_year: 2024,
    created_at: '2024-04-10T13:45:00Z',
    author: 'Mediterranean Climate Network',
    likes: 287,
    shares: 74,
    views: 4567,
    tags: ['mediterranean', 'drought', 'agriculture', 'water-stress'],
    thumbnail_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    category: 'community_research',
    is_public: true,
  },
  {
    id: '8',
    session_id: 'sample_session_8',
    title: 'Tropical Peatland Conservation Monitoring',
    description: 'Tracking peatland restoration efforts in Southeast Asia and their impact on carbon sequestration.',
    query: 'What is the vegetation recovery in tropical peatlands from 2018 to 2024?',
    coordinates: {
      southwest_lat: -10.0,
      southwest_lon: 95.0,
      northeast_lat: 10.0,
      northeast_lon: 140.0,
    },
    location_name: 'Southeast Asian Peatlands',
    start_year: 2018,
    end_year: 2024,
    created_at: '2024-03-28T15:20:00Z',
    author: 'Peatland Restoration Agency',
    likes: 167,
    shares: 45,
    views: 3234,
    tags: ['peatlands', 'restoration', 'carbon', 'southeast-asia'],
    thumbnail_url: 'https://images.unsplash.com/photo-1574452969969-7fb3bbef4056?w=400&h=300&fit=crop',
    category: 'community_research',
    is_public: true,
  },

  // Enterprise Repository
  {
    id: '9',
    session_id: 'sample_session_9',
    title: 'Corporate Forest Carbon Offset Verification',
    description: 'Internal analysis of company-owned forest lands for carbon credit verification and ESG reporting.',
    query: 'What is the forest growth in our carbon offset areas from 2020 to 2024?',
    coordinates: {
      southwest_lat: 45.5,
      southwest_lon: -75.0,
      northeast_lat: 46.5,
      northeast_lon: -74.0,
    },
    location_name: 'Quebec Forest Holdings',
    start_year: 2020,
    end_year: 2024,
    created_at: '2024-07-30T12:00:00Z',
    author: 'GreenTech Corp ESG Team',
    likes: 23,
    shares: 5,
    views: 234,
    tags: ['carbon-offset', 'esg', 'forest-management', 'verification'],
    thumbnail_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    category: 'enterprise_repository',
    is_public: false,
  },
  {
    id: '10',
    session_id: 'sample_session_10',
    title: 'Supply Chain Risk Assessment - Palm Oil',
    description: 'Monitoring deforestation risk in palm oil supply chain areas for sustainability compliance.',
    query: 'What are the deforestation patterns in our palm oil supply regions from 2019 to 2024?',
    coordinates: {
      southwest_lat: 0.0,
      southwest_lon: 110.0,
      northeast_lat: 7.0,
      northeast_lon: 119.0,
    },
    location_name: 'Borneo Supply Chain Regions',
    start_year: 2019,
    end_year: 2024,
    created_at: '2024-07-15T09:30:00Z',
    author: 'Supply Chain Analytics',
    likes: 18,
    shares: 3,
    views: 156,
    tags: ['supply-chain', 'palm-oil', 'deforestation', 'compliance'],
    thumbnail_url: 'https://images.unsplash.com/photo-1574452969969-7fb3bbef4056?w=400&h=300&fit=crop',
    category: 'enterprise_repository',
    is_public: false,
  },
  {
    id: '11',
    session_id: 'sample_session_11',
    title: 'Agricultural Investment Performance',
    description: 'Evaluation of vegetation health and productivity across company agricultural investments.',
    query: 'How productive are our agricultural investments from 2021 to 2024?',
    coordinates: {
      southwest_lat: -25.0,
      southwest_lon: -60.0,
      northeast_lat: -20.0,
      northeast_lon: -55.0,
    },
    location_name: 'Argentina Agricultural Portfolio',
    start_year: 2021,
    end_year: 2024,
    created_at: '2024-06-20T14:45:00Z',
    author: 'Investment Analytics Team',
    likes: 31,
    shares: 7,
    views: 289,
    tags: ['agriculture', 'investment', 'productivity', 'argentina'],
    thumbnail_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
    category: 'enterprise_repository',
    is_public: false,
  },
  {
    id: '12',
    session_id: 'sample_session_12',
    title: 'Renewable Energy Site Vegetation Impact',
    description: 'Assessment of vegetation changes around wind farm installations for environmental compliance.',
    query: 'What is the vegetation impact around our wind farms from 2018 to 2024?',
    coordinates: {
      southwest_lat: 40.0,
      southwest_lon: -5.0,
      northeast_lat: 43.0,
      northeast_lon: -2.0,
    },
    location_name: 'Spanish Wind Farm Portfolio',
    start_year: 2018,
    end_year: 2024,
    created_at: '2024-05-05T16:10:00Z',
    author: 'Environmental Compliance',
    likes: 15,
    shares: 2,
    views: 123,
    tags: ['wind-energy', 'environmental-impact', 'compliance', 'spain'],
    thumbnail_url: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&h=300&fit=crop',
    category: 'enterprise_repository',
    is_public: false,
  },
];

export const getAnalysesByCategory = (category: AnalysisCard['category']): AnalysisCard[] => {
  return sampleAnalyses.filter(analysis => analysis.category === category);
};

export const getRecentAnalyses = (limit?: number): AnalysisCard[] => {
  const sorted = [...sampleAnalyses].sort((a, b) => 
    new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
  return limit ? sorted.slice(0, limit) : sorted;
};

export const searchAnalyses = (query: string): AnalysisCard[] => {
  const lowerQuery = query.toLowerCase();
  return sampleAnalyses.filter(analysis => 
    analysis.title.toLowerCase().includes(lowerQuery) ||
    analysis.description.toLowerCase().includes(lowerQuery) ||
    analysis.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    analysis.location_name.toLowerCase().includes(lowerQuery)
  );
};